[project]
name = 'property-management-excellence'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.property-ops-support]
path = 'contracts/property-ops-support.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-delivery-qa]
path = 'contracts/service-delivery-qa.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
